# .binder/environment.yml
name: ambitus
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - pip
  - pip:
      - pingouin          # ICC, ANOVA
      - statsmodels       # robusztus stat tesztek
